### ISSUE TITLE
media-utils install failing in Node-RED

### ISSUE THREAD

**Issue by emmajdaws** [ibm-early-programs/node-red-contrib-media-utils#10]
Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-media-utils@0.0.6
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

**Comment by chughts** [comment]
Looks like an indirect dependancy has been deprecated. How were you installing the nodes? We may need to bring all dependancies unto date to remove the deprecation warning.

**Comment by emmajdaws** [comment]
via manage palette. Tried on 2 instances in the German region and failed. Just tried in US and it installed ok.

**Comment by chughts** [comment]
The failing module is request. The latest version of request uses uuid. So will try fixing by bumping dependency on request to latest version.

**Comment by chughts** [comment]
Fixed in release 0.0.7
