### ISSUE TITLE
Microphone and Camera input nodes incorrectly report unsupported browser.

### ISSUE THREAD

**Issue by cody-code-wy** [ibm-early-programs/node-red-contrib-media-utils#17]
Microphone and Camera report browser does not support recording on versions of Safari that do include such APIs. 

On Safari Version 12.1 attesting to interact with a microphone or camera node will create an alert reading "Your browser does not support audio recording", though since Safari Version 11 the getUserMedia/Stream APIs have been fully implemented.

**Comment by chughts** [comment]
This is the wrong project. Camera and Microphone are in node-red-contrib-browser-utils.
The safari support has been fixed in version 0.0.9 of those nodes.
