### ISSUE TITLE
mp3 audio output?

### ISSUE THREAD

**Issue by spants** [ibm-early-programs/node-red-contrib-media-utils#2]
Would it be possible to add support for mp3 output to buffer? 
This is required by a device that I would like to use.

**Comment by yrezgui** [comment]
Hi @spants, the issue during the development of this node is we find out not every browser is accepting mp3. Did you play with the ffmpeg node to get an mp3 file?

**Comment by spants** [comment]
Hi - I would just like to be able to do the conversion to mp3 (saved in a buffer rather than playing in a browser) from the output from the text-to-speech node in Watson.

Watson supports these Audio formats: Produces Ogg format with the opus codec (the default), Waveform Audio File Format (WAV), Free Lossless Audio Codec (FLAC), Linear 16-bit Pulse-Code Modulation (PCM), mu-law (u-law), or basic audio - and I would like to convert one of these to MP3.

**Comment by chughts** [comment]
If there is demand this is something that we can add. Which device is it that is requiring a mp3 output?

**Comment by psyntium** [comment]
i created a fork and added mp3. one of the usage is for alexa. since alexa only supports MP3 for its SSML.

**Comment by chughts** [comment]
@psyntium you need to accept the CLA, and default setting should remain as something that is Watson STT friendly.

**Comment by chughts** [comment]
published in 0.0.4
